name: buzzardos-local

services:
  desktop:
    image: ${BUZZARDOS_OCI_TAG:-buzzardos-desktop:local}
    build:
      context: ..
      dockerfile: oci/desktop/Containerfile
      platforms:
        - linux/amd64
