[package]
name = "buzzardos-desktop"
version = "0.1.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
accesskit.workspace = true
accesskit_unix.workspace = true
anyhow.workspace = true
fontdue.workspace = true
gio.workspace = true
image.workspace = true
libc.workspace = true
resvg.workspace = true
serde.workspace = true
serde_json.workspace = true
smithay-client-toolkit.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
wl-clipboard-rs.workspace = true
buzzardos-desktop-core = { path = "../desktop-core" }
buzzardos-shortcut-helper = { path = "../shortcut-helper", default-features = false }

[dev-dependencies]
tempfile.workspace = true
