[package]
name = "wildbuzzard-shortcut-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["chooser"]
chooser = ["dep:gtk4"]

[dependencies]
anyhow.workspace = true
gio.workspace = true
glib.workspace = true
gtk4 = { workspace = true, optional = true }
image.workspace = true
libc.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
wildbuzzard-desktop-core = { path = "../desktop-core" }

[dev-dependencies]
tempfile.workspace = true

[lib]
name = "wildbuzzard_shortcut_helper"
path = "src/lib.rs"

[[bin]]
name = "wildbuzzard-shortcut-helper"
path = "src/main.rs"
