[package]
name = "wildbuzzard-display"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
gtk4.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
wayland-protocols.workspace = true
wayland-server.workspace = true
xkbcommon.workspace = true
wb-core = { path = "../wb-core" }

[dev-dependencies]
tempfile.workspace = true
