[package]
name = "wildbuzzard-desktop-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["xdg-discovery"]
xdg-discovery = ["dep:gio", "dep:glib"]

[dependencies]
gio = { workspace = true, optional = true }
glib = { workspace = true, optional = true }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
