[package]
name = "wildbuzzard-settings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gio.workspace = true
glib.workspace = true
gtk4.workspace = true
libc.workspace = true
libpulse-binding.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
wildbuzzard-desktop-core = { path = "../desktop-core" }

[dev-dependencies]
tempfile.workspace = true

[lints.rust]
unsafe_code = "forbid"

[[bin]]
name = "wildbuzzard-settings"
path = "src/main.rs"
