#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
set -eu

install -d -m 0700 -o 1000 -g 1000 /run/user/1000
install -d -m 0755 /run/wildbuzzard

if [ ! -s /etc/machine-id ]; then
    systemd-machine-id-setup
fi

exec /lib/systemd/systemd --system
